title: Maria Osomo-Obialor
logo: Data image.jpg
description: Skilled in SQL, Excel, and Power BI to turn complex data into insights, enabling data-driven decisions with excellent analytical, problem-solving, and presentation abilities.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
