title: Maria Osomo-Obialor
logo: Data image.jpg
description: I have expertise in translating difficult data into insights utilising tools such as SQL, Excel, and Power BI. I possess strong analytical, problem-solving, and presentation abilities to help with data-driven business decisions and predictive modelling.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
